version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app_network
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: brazf/estoque:latest
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      DB_SERVER: mysql-container
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PROFILE: ${APP_PROFILE}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_DURATION: ${JWT_DURATION}
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  mysql-data:
    driver: local