FROM openjdk:17-jdk-alpine

# Definindo variáveis de ambiente diretamente, se necessário
ENV DB_SERVER=${DB_SERVER}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV APP_PROFILE=${APP_PROFILE}
ENV CLIENT_ID=${CLIENT_ID}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV JWT_DURATION=${JWT_DURATION}
ENV CORS_ORIGINS=${CORS_ORIGINS}

COPY /estoque/target/estoque-0.0.1-SNAPSHOT.jar estoque.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/estoque.jar"]
