name: Deploy Application
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: build
      run: |
        cd estoque
        mvn clean verify package
  
    - name: Login Docker
      run: docker login -u brazf -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build docker image
      run: docker build -t brazf/estoque .
    - name: Push image docker
      run: docker push brazf/estoque
    - name: Save JaCoCo Report
      if: success()
      run: |
        mv estoque/target/site/jacoco/jacoco.csv jacoco.csv
      continue-on-error: false
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: jacoco.csv

  generate-badge:
    name: Generate Badge
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Download JaCoCo Report
      uses: actions/download-artifact@v3
      with:
        name: jacoco-report
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Create Badge Directory
      run: mkdir -p .github/badges
  
    - name: Generate Coverage Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: jacoco.csv
        badges-directory: .github/badges
        coverage-badge-filename: coverage-badge.svg
        generate-coverage-badge: true

    - name: List Badge Directory
      run: |
        echo "Conteúdo de .github/badges:"
        ls -la .github/badges

    - name: Print README Before Update
      run: |
        echo "Conteúdo atual do README.md:"
        cat README.md

    - name: Add Badge to README
      run: |
        BADGE_MARKDOWN="![Cobertura de Testes](.github/badges/coverage-badge.svg)"
        if grep -q "![Cobertura de Testes]" README.md; then
          sed -i "s|!\[Cobertura de Testes\](.*)|$BADGE_MARKDOWN|" README.md
        else
          echo -e "$BADGE_MARKDOWN\n\n$(cat README.md)" > README.md
        fi

    - name: Print README After Update
      run: |
        echo "Conteúdo do README.md após atualização:"
        cat README.md

    - name: Commit Coverage Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Atualização do badge de cobertura"
        file_pattern: ".github/badges/coverage-badge.svg README.md"

    - name: Upload Coverage Badge
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: .github/badges/coverage-badge.svg
      
  deploy:
    needs: generate-badge
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pull image from docker hub
      run: docker pull brazf/estoque:latest

    - name: Create .env file
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "APP_PROFILE=${{ secrets.APP_PROFILE }}" >> .env
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
        echo "JWT_DURATION=${{ secrets.JWT_DURATION }}" >> .env
        echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}" >> .env
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

    - name: Stop and remove existing containers
      run: |
        cd /home/ubuntu
        docker-compose down || true

    - name: Deploy application with docker-compose
      run: |
        cd docker
        docker-compose up -d --env-file ../.env
