name: Deploy Application
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: build
      run: |
          cd estoque
          mvn clean package -X
  
    - name: Login Docker
      run: docker login -u brazf -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build docker image
      run: |
          docker build \
          --build-arg DB_SERVER=${{secrets.DB_SERVER}} \
          --build-arg DB_NAME=${{secrets.DB_NAME}} \
          --build-arg DB_USERNAME=${{secrets.DB_USERNAME}} \
          --build-arg DB_PASSWORD=${{secrets.DB_PASSWORD}} \
          --build-arg APP_PROFILE=${{secrets.APP_PROFILE}} \
          --build-arg CLIENT_ID=${{secrets.CLIENTID}} \
          --build-arg CLIENT_SECRET=${{secrets.CLIENTSECRET}} \
          --build-arg JWT_DURATION=${{secrets.JWT_DURATION}} \
          --build-arg CORS_ORIGINS=${{secrets.CORS_ORIGINS}} \
          -t brazf/estoque .

    - name: Push image docker
      run: docker push brazf/estoque

  deploy:
    needs: build
    runs-on: self-hosted
    steps:

    - name: Pull image from docker hub
      run: docker pull brazf/estoque:latest
      
    - name: docker remove container
      run: docker rm -f deploy_backend

    - name: Run docker container
      run: docker run -d --restart unless-stopped -p 80:8080 --name deploy_backend brazf/estoque
      