name: Deploy Application
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: build
      run: |
          cd estoque
          mvn clean package -X
  
    - name: Login Docker
      run: docker login -u brazf -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build docker image
      run: docker build -t brazf/estoque .
    - name: Push image docker
      run: docker push brazf/estoque
    - name: Save JaCoCo Report
      if: success()
      run: |
        mv estoque/target/site/jacoco/jacoco.xml jacoco.xml
      continue-on-error: false

  generate-badge:
      name: Generate Badge
      runs-on: ubuntu-latest
      needs: build
      steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
  
      - name: Generate Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-xml: jacoco.xml
          badge-output: coverage-badge.svg

      - name: Commit Coverage Badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização do badge de cobertura"
          file_pattern: coverage-badge.svg

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    - name: Pull image from docker hub
      run: docker pull brazf/estoque:latest
    
    - name: Stop and remove existing containers
      run: |
        cd /home/ubuntu
        docker-compose down || true

    - name: Deploy with docker-compose
      run: |
        cd /home/ubuntu
        docker-compose up -d
