name: Deploy Application
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: build
      run: |
          echo "Entrando no diretório 'estoque' e iniciando o build..."
          cd estoque
          mvn clean verify package
          echo "Build concluído."
          echo "Listando arquivos gerados em 'target':"
          ls -R target
          echo "Verificando 'target/site/jacoco':"
          ls -R target/site/jacoco || echo "Diretório 'target/site/jacoco' não encontrado!"
  
    - name: Login Docker
      run: docker login -u brazf -p ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build docker image
      run: docker build -t brazf/estoque .
    - name: Push image docker
      run: docker push brazf/estoque
    - name: Save JaCoCo Report
      if: success()
      run: |
        echo "Movendo o arquivo 'jacoco.csv' para o diretório raiz do projeto..."
        mv estoque/target/site/jacoco/jacoco.csv jacoco.csv
        echo "Movido com sucesso. Verificando o diretório atual:"
        ls -R .
      continue-on-error: false
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: jacoco.csv

  generate-badge:
    name: Generate Badge
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Download JaCoCo Report
      uses: actions/download-artifact@v3
      with:
        name: jacoco-report
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Confirm JaCoCo CSV Exists
      run: |
        echo "Confirmando a presença do arquivo 'jacoco.csv' antes de gerar o badge:"
        ls -R
        if [ ! -f "jacoco.csv" ]; then
          echo "Erro: Arquivo 'jacoco.csv' não encontrado!"
          exit 1
        fi
        echo "Arquivo encontrado. Prosseguindo..."
  
    - name: Generate Coverage Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: jacoco.csv
        badges-directory: .github/badges
        coverage-badge-filename: coverage-badge.svg
        generate-coverage-badge: true

    - name: Commit Coverage Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Atualização do badge de cobertura"
        file_pattern: coverage-badge.svg

  deploy:
    needs: generate-badge
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pull image from docker hub
      run: docker pull brazf/estoque:latest
    
    - name: Stop and remove existing containers
      run: |
        cd /home/ubuntu
        docker-compose down || true

    - name: Deploy with docker-compose
      run: |
        cd /home/ubuntu
        docker-compose up -d
